config/routes.rb
Second::Application.routes.draw do

  

  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  
  resources :topics  do
    resources :replies
  end
  
  match "/logout" =>'sessions#logout',:as => "logout"
 
  resources :sessions
  resources :users 
  
  match "/changepass" => "users#changepass",:as => "changepass"  

  root :to =>  'topics#index'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user 

  validates :content ,  :presence => true, :length => {:within => 2..2000}
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  
  before_filter :find_topic
  def create
    @reply = @topic.replies.build(params[:reply])
    @reply.user_id = current_user.id
    if @reply.save
      redirect_to topic_path(@topic)
    else
      redirect_to topic_path(@topic)
    end
  end
  
  def edit
    @reply = Reply.find(params[:id])
  end

  def update
    @reply = Reply.find(params[:id])
#    @reply.content =  params[:reply][:content]

    if @reply.update_attributes(params[:reply])
      flash[:notice] = "回帖更新成功."
      redirect_to topic_path(@reply.topic_id)
    else
      render :action => "edit"
    end

  end
 
  def find_topic
    @topic = Topic.find(params[:topic_id])
  end

end

app/views/replies/_reply.html.erb

<div class="reply" id="reply<%= @reply_counter %>">
  <div class="pull-left face"><%=  getavatar(reply.user,:normal) %></div>
  
  <div class="pull-right">
    <%if owner?(reply) %>
      <a href="<%= edit_topic_reply_path(@topic,reply)%>" title="修改"><i class="icon-pencil"></i></a>
    <% end %>
  </div>
  <div class="infos">
    <div class="info">
     <span class="name">
        <%= @reply_counter %><%= t("common.floor")%>,
        <%= link_to reply.user.netname,reply.user %>,
        <%= time_ago_in_words(reply.created_at) %>
      </span>
    </div>
    <div class="body">
        <% if reply.content.blank? %>
          .       
        <% else %>
      <%= simple_format(reply.content) %>
        <% end %>
    </div>
  </div>
</div>
  <% @reply_counter +=  1 %>

app/views/replies/edit.html.erb
<%= render "shared/breadcrumb" ,links: [["首页",root_path],["论坛",topics_path],[@topic.node.name ,@topic.node],["浏览帖子",""]] %>
<div id="main" class="container-fluid">
  <div class="content">
    <div class="box">
      <%= simple_form_for([@topic,@reply]) do |f| %>
        <fieldset>
          <legend><%= t("reply.edit_reply") %></legend>
          <%= f.input :content , :as => :text , :input_html => {:class => "topic_editro xxlarge",:rows => "15"}%>
          <div class="form-actions">
            <%= f.submit t("common.save"),:class => "btn btn-primary",'data-disable-width' => t("common.saving")%>
            <a href="<%= topic_path(@topic)%>" class="btn"> <%= t("common.cancel")%> </a>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>  
  
  <%= render "shared/sidebar" %>
</div>