config/routes.rb
Second::Application.routes.draw do

  

  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  
  resources :topics  do
    resources :replies
  end
  
  match "/logout" =>'sessions#logout',:as => "logout"
 
  resources :sessions
  resources :users 
  
  match "/changepass" => "users#changepass",:as => "changepass"  

  root :to =>  'topics#index'

end

app/models/topic.rb

class Topic < ActiveRecord::Base
  validates :title ,  :presence => true, :length => {:within => 5..30}
  validates :content ,:presence => true, :length => {:within => 5..2000}
  
  belongs_to :node
  belongs_to :user
  belongs_to :last_reply_user ,:class_name => "User"

  has_many :replies

#  scope :fields_for_list ,where(:replycount => 0)

end

app/controllers/admin/topic_controller.rb
class Admin::TopicController < ApplicationController
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  before_filter :check_login
  def index
    @topics = Topic.select("id,title,node_id,user_id,last_reply_user_id,last_replytime,replycount,updated_at,created_at").order("last_replytime desc").includes(:user).paginate(:page=> params[:page],:per_page => 15)
  end
  
  def show
    @topic = Topic.find(params[:id])
    Topic.record_timestamps = false
    @topic.readtimes += 1
    @topic.save
    Topic.record_timestamps = true 
    @replies = @topic.replies.includes(:user).order("created_at")
    @reply_counter = 1 
    @nreply = Reply.new
  end
  def new
    @topic= Topic.new
  end

  def create
    pt = params[:topic]
    @topic =Topic.new(pt)
    @topic.user_id = current_user.id
    @topic.last_replytime = Time.now
    if @topic.save
      redirect_to topic_path(@topic)
    else
      render :action => "new"
    end

  end
  
  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    pt = params[:topic]
    @topic.node_id =  pt[:node_id]
    @topic.title = pt[:title]
    @topic.content = pt[:content]
    @topic.unreply_all = pt[:unreply_all]
    @topic.unreply_other = pt[:unreply_other]
  
    if @topic.save
      flash[:notice] =   t("topics.update_topic_success")
      redirect_to topic_path(@topic.id) 
    else
      render :action => "edit"
    end
  end

  def destroy
    #flash[:notice] = "暂时还没有实现删除帖子的功能！"
    #render :action => "show"
  end  
  def node
    @node = Node.find(params[:id])
    @topics = @node.topics.includes(:user)
   # @topics = @node.topics.last_actived.fields_for_list.includes(:user).paginate(:page => params[:page],:per_page => 15)
   # set_seo_meta("#{@node.name} &raquo; #{t("menu.topics")}","#{Setting.app_name}#{t("menu.topics")}#{@node.name}",@node.summary)
   # drop_breadcrumb("#{@node.name}")
    render :action => "index" #, :stream => true
  end

end

app/helpers/admin/topic_helper.rb
module Admin::TopicHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for @topic  do |f| %>
  <fieldset>
    <legend><%= @topic.new_record? ?  t("topics.create_topic") : t("topics.edit_topic") %></legend>
    <%= render "shared/error_messages",:target => @topic%> 
    标题：<span class="node_select"><%= f.select :node_id,options_for_select(Node.all.map{|node| [node.name,node.id]}, @topic.node_id)%></span>
    <%= f.text_field :title,:class => "span4" %>
    <div class="control-group">
        <%= f.label :content,"正文", :class => "control-label" %>
        <div class="controls">
          <%= f.kindeditor :content,:as => :kindeditor,:input_html => { :simple_mode => true } %>
        </div>
    </div>
    
    <div class="submit-button">
      <%= f.submit "保存" ,:class =>"btn btn-primary btn-large pull-right" %>
    </div>
    <div class = "control-group">
     <label class="checkbox"> <%= f.check_box :unreply_all %> <%= t("topics.unreply_all") %> </label>
     <label class="checkbox"> <%= f.check_box :unreply_other %> <%= t("topics.unreply_other") %> </label>
    </div>
  </fieldset>
<% end %>

app/views/topics/_node_list.html.haml
%section#stats.box
  %strong 论坛节点
  %ul
    - Node.all.each do |node|
      %li= link_to "#{node.name}(#{node.topics.count})" ,node

app/views/topics/_topic_info.html.erb
<div class="infos">
  <div class="pull-right avatar_normal"><%= getavatar(topic.user,:normal) %></div>
  <h1><%= truncate(topic.title, :length => 100) %></h1>
  <div class="info leader">
    <%= link_to topic.node.name,topic.node %>
    •
    <%= link_to topic.user.netname, topic.user %>
    •
    <%= t("common.created_at",:time=> time_ago_in_words(topic.created_at))%>
    •
    <%= topic.readtimes %><%= t("common.read_times") %>
  </div>
</div>

app/views/topics/_topic_list.html.erb
<%if @topics.blank? %>
  <div class="alert alert-success">亲，该版块等你多时了，点这里发帖。<%= link_to "发帖",new_topic_path,:class => "btn"%></div>
<% else %>
<% @topics.each do |topic| %>
<div class="topic topic_line">
  <div class="pull-left avatar">
    <%=  getavatar(topic.user,:normal) %>
  </div>
  <div class="right_info">
    <div class="pull-right replies">
      <% if topic.replycount? %>
          <span class = "badge badge-success" > <%=  topic.replycount %> </span>
      <% end %>
    </div>
    <div class="infos">
      <div class="title">
        <%= link_to(truncate(topic.title, :length => 100), topic_path(topic), :title => topic.title) %>
      </div>
      <div class="info">
        <%=  link_to(topic.node.name, topic.node, :class => "node") %>
        •
        <%= link_to(topic.user.netname, topic.user) %> 
        •
        <% if topic.last_reply_user_id? %>
        <%= t("common.last_by")%> <%= link_to  topic.last_reply_user.netname ,user_path(topic.last_reply_user_id) %> <%=t("common.reply_at",:time => time_ago_in_words(topic.last_replytime )) %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/topics/_topic_list.html.haml
- @topics.each do |topic|
  %div.topic.topic_line
    %div.pull-left.avatar
      %img(src="/assets/normal.png")
    %div.right_info
      %div.pull-right.replies
        = link_to "12",topic_path(topic),class: "count state_true"
    %div.infos
      %div.title
        = link_to(truncate(topic.title, :length => 100), topic_path(topic), :title => topic.title)
      %div.info
        = link_to topic.node.name,topic.node
        •
        = link_to topic.user.netname,topic.user
        = "发表于 #{time_ago_in_words(topic.created_at)} 之前"
       %span.badge.badge-info 18

app/views/topics/edit.html.erb
<% @title = "修改" %>
<%= render 'shared/breadcrumb',links:[["首页",""],["社区",topics_path],["修改帖子",""]] %>
<div id="main" class="container-fluid" >
<div class = "content">
  <div class= "box">
    <%= render "form" %>
  </div>
</div>
<%= render "shared/sidebar" %>
</div>

app/views/topics/index.html.erb
<% @title = "南翔人论坛" %>
<%= render "shared/breadcrumb" ,links: [["首页",root_path],["论坛",""]] %> 
<div id="main" class="container-fluid">
  <div class="content">
    <div class="box box_gray">
      <div id="node_info"> 
        <h2>最新更新的帖子</h2>
      </div>
      <div class="topics">
        <%= render :partial => 'topic_list' %> 
      </div>
      <%= will_paginate @topics %>
    </div>
  </div>
  <%= render "shared/sidebar"  %>
</div>

app/views/topics/index.html.haml
= render "shared/breadcrumb" ,links: [["首页",root_path]]

%div.content
  %div.box.box_gray
    %div.topics
      = render  "topics/topic_list", topics:  @topics

%section#row-fluid
  %section.row
    %section.span3.box
      =link_to "发布新帖",new_topic_path,class:"btn btn-success"
  %section.row
    %section.span3.box
      %ul
        %li 社区会员：503人
        %li 帖子数：788篇
        %li 回帖数:1233条
    %section.span3.box
      = render :partial => 'node_list'

app/views/topics/new.html.erb
<% @title = "发帖" %>
<%= render 'shared/breadcrumb',links:[["首页",""],["社区",topics_path],["发贴",""]] %>
<div id="main" class="container-fluid">
<div class="content">
  <div class="box">
    <%= render "form" %>
  </div>
</div>
<%= render "shared/sidebar" %> 
</div>

app/views/topics/new.html.haml
= render 'shared/breadcrumb',links:[["首页",""],["社区",topics_path],["发贴",""]]
%section#new_topic.box
  %h1 新建帖子
  = form_for @topic , html:{class: "form-horizotal"} do |f|
    .control-group
      =f.label :title ,"标题",class: "control-label"
      .controls
        =f.select :node_id,options_for_select(Node.all.map{|node| [node.name,node.id]})
        =f.text_field :title
    .control-group
      =f.label :content,"正文", class: "control-label"
      .controls
        =f.text_area :content ,rows: 20
    .submit-button
      %input(type="submit" value="保存" class="btn btn-primary")
      = link_to "取消"
%section#sidebar
  %section#new_post_note.box
    %h2 发贴问题
    %p 没什么可说的，发就是了
  

app/views/topics/show.html.erb
<% @title = @topic.title %>
<%= render "shared/breadcrumb" ,links: [["首页",root_path],["论坛",topics_path],[@topic.node.name ,@topic.node],["浏览帖子",""]] %>
<div id="main" class="container-fluid">
  <div class="content">
    
    <div id="topic_show" class="topics box hfeed">
      <div class="topic hentry">
        <%= render :partial => "topics/topic_info", :locals => { :topic => @topic} %>
        <div class="body entry-content">
          <%= raw( @topic.content) %>
        </div> 
        <div class="tools">
          <% if  owner?(@topic) %>
            <a href = "<%= edit_topic_path(@topic) %>" title="修改"><i class="icon-pencil"></i></a>
           <!-- <a href = "<%= topic_path(@topic) %>" data-confirm="确定要删除么？" data-method="delete" rel="nofollow" title="删除"><i class="icon-remove"></i></a> -->
          <% end %>
        </div>
      </div>
    </div>

    <% if @replies.blank? %>
      <div class="no_result">
        <%= t("topics.no_replies") %>
      </div>
    <% else %>
      <div id="replies" class="box">
        <div class="total">
          共收到 <b><%= @topic.replycount %></b> 条回复
        </div>
        <%= render :partial => "replies/reply" ,:collection => @replies %>
      </div>
    <% end %>

    <% if @topic.unreply_fromAdmin %>
       <div class="alert"><%= t("topics.unreply_fromAdmin")%></div>
    <% else %>
      <% if @topic.unreply_all %>
        <div class="alert"><%= t("topics.unreply_all")%></div>
      <% else %>
        <% if @topic.unreply_other  and @topic.user != current_user%>
          <div class="alert"><%= t("topics.unreply_other")%></div>
        <% else %>
          <div id="reply" class="form box">
            <%= form_for @nreply, :url => topic_replies_path(@topic) do |f| %>
              <%= render "shared/error_messages",:target => @nreply%> 
              <%= f.text_area :content ,:rows => 4 %>
              <%= f.submit "提交回复",:class => "btn btn-primary" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>

   </div>
  <%= render "shared/sidebar"  %>
</div>

app/views/topics/show.html.haml
= render 'shared/breadcrumb',links: [["首页",root_path],["论坛",topics_path],[@topic.node.name,@topic.node],["浏览帖子",""]]
%section#show_topic
  %section#topic_banner.box.info-box
    %h1=@topic.title
    %p.topic_info
      = link_to @topic.node.name,@topic.node,class:"node"
      = link_to @topic.user.netname,@topic.user
      %span= " . "
      ="发布于#{time_ago_in_words(@topic.created_at)} 之前"
  %section#topic_content.box
    %p=@topic.content
  
  %section#replies_banner.box.info-box
    %span
      - if @replies.blank?
        = "没有回复"
      - else
        = "共收到 #{@replies.count} 条回复"

  %section#replies.box
    %ul
      - @replies.each do |r|
        %li
          %a.span1(href="")
            %img(src="/assets/normal.png")
          %article.span8
            =link_to r.user.netname,r.user,class: "user_link"
            %span= "回复于 #{time_ago_in_words(r.created_at)} 之前"
            %p= raw( r.content).html_safe
            
  %section#reply.box
    =form_for Reply.new ,remote:false,url: topic_replies_path(@topic) do |f|
      =f.text_area :content,rows:4
      %input(type="submit" class="btn btn-primary" value="提交回复")