config/routes.rb
Second::Application.routes.draw do

  

  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  
  resources :topics  do
    resources :replies
  end
  
  match "/logout" =>'sessions#logout',:as => "logout"
 
  resources :sessions
  resources :users 
  
  match "/changepass" => "users#changepass",:as => "changepass"  

  root :to =>  'topics#index'

end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base

  #确认密码验证 
  attr_accessor   :password, :password_confirmation,:oapass
  attr_accessible :password, :password_confirmation,:oapass,:avatar
  validates_confirmation_of :password,  :message => "两次输入的密码不一致!"
  
  attr_accessible :username,:netname,:oacode,:telephone,:truename,:isadmin
   
  #校验 不能为空
 # validates_presence_of :username, :netname,  :truename,:password , :on => "create"
  
  validate :check_easuser  ,:on => :create,:if => :input_oacode?
  #校验 不能重复
   validates_uniqueness_of :username,:on => :create ,:message => "你的用户名已经被占用了，重输一个^_^"

  validates :netname ,  :presence => true, :length => {:within => 2..10}
  #EAS用户校验 
  validates_uniqueness_of :oacode ,:on => :create,:message => "该OA号码已在本论坛注册，不可再用。",:if => :input_oacode? 

  #用户图像--------------------------------------------------------------------------------------------
  attr_accessible :avatar
  has_attached_file :avatar,
    :styles => {  :big => "120x120>", :normal => "48x48>", :small => "16x16>" ,:large => "64*64>"},
    :default_sytle => "normal",
    :url => "/uploadfiles/:class/:attachment/:id/:style.:extension",
    :path => ":rails_root/public/uploadfiles/:class/:attachment/:id/:style.:extension"
  validates_attachment_content_type :avatar,
    :content_type =>[ "image/gif",'image/png','image/x-png','image/jpeg','image/pjpeg','image/jpg'],
    :message => "头像文件需要是图片格式。如：png,jpg.jpeg,gif等"

#-------------------------------------------------------------------------------------------------------
  has_many :topics
  has_many :replies


  # password 是个虚拟属性
  def password
    @password
  end
  
  def password=(password)
    @password=password
    return if password.blank?
    create_new_salt
    self.encrypted_password = User.encrypted_password(self.password,self.salt)
  end

  def oapass
    @oapass
  end

  def oapass=(oapass)
    @oapass=oapass
  end


  def self.authentication(name,password="")
    user = User.find_by_username(name)
    if user
      expected_password = encrypted_password(password.to_s,user.salt)
      p expected_password
      if expected_password != user.encrypted_password
        user = nil
      end
    end    
    user
  end
 
  def admin?
    self.isadmin?
  end
 
  private
  
  def input_oacode?
    oacode.present?
  end
  #实现SHA1加密
  def self.encrypted_password(password ="",salt)
    string_to_hash = password + "song" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end  
  #给salt赋值
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  #判断是否为初始密码
  def check_defalutpass?
     oacode == oapass or oapass == '111111'
  end    
  #eas用户校验 
  def check_easuser
    if not  oacode.blank?
      a =  ActiveRecord::Base.connection.select_all "select username,checkpass('#{oacode}' ,'#{oapass}' ) ispass,status from oadb.system_users where fnumber= '#{oacode}' "
      if a.count == 0 
        errors.add(:oacode,'不存在该OA编码!,你是何人？')
      else
        u = a.first
        errors.add(:oapass ,"OA用户名密码不正确！")  if  u["ispass"] != "1"     
  #      errors.add(:oacode ,"真实姓名与OA不一致！")  if  u["username"] != truename
        errors.add(:oacode ,"该OA用户已被禁用！") if u["status"] != "1"
        self.netname = u["username"] if netname.blank?
        self.username = oacode 
        self.truename = u["username"]
        self.password = oapass
      end
    end
  end
  
  def chcck_easuser_status(fnumber)
    a= ActiveRecord::Base.connection.select_all "select status from oadb.system_users where fnumber = '#{fnumber}'"
    u = a.first
    return u["status"] == '1'
  end      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :check_login, :only=>[:index,:show]
  def index
    @newusers = User.where("oacode is not null").order("created_at DESC").paginate(:page=> params[:page],:per_page => 60)
    @unusers = User.where(:oacode => nil).order("created_at DESC")   
  end

  def new
    @user= User.new
  end
  
  def create
    #用户名是否被注册
   # euser= User.find_by_username(params[:user][:username])
    
   @user= User.new(params[:user]) 
    if @user.save 
      #session[:user_id]= @user.id
      flash[:notice] = "注册成功，登录后可访问论坛。"
      redirect_to new_session_path
    else
      render :action => "new"    
    end
  end    

  def show
    @user = User.find(params[:id])
    @topics = @user.topics.order("created_at desc").includes(:node).limit(10)
    @replies = @user.replies.order("created_at desc").includes(:topic).limit(10)
  end
  
  def edit
    @user=current_user
  end

  def update

    @user = current_user
    if params[:user][:netname] != @user.netname
     @user.netname = params[:user][:netname] 
    end
    if params[:user][:avatar] 
       @user.avatar = params[:user][:avatar]
    end
    if @user.save   
      #@user.update_attribute("netname",params[:user][:netname])
      flash[:notice]  = "用户信息修改成功！"
      redirect_to user_path(@user)
    else
      render :action =>"edit"
    end
  end


# 修改密码
  def changepass
    @user = current_user    
    if  params[:newpass] == params[:newpass_confirm] 
      s = User.authentication(current_user.username,params[:oldpass]) 
      if s 
        @user.password = params[:newpass]
        if @user.save
          flash[:notice] = "密码修改成功!"
          redirect_to user_path(@user)
        else
          flash[:notice] = "修改密码失败!"
          redirect_to edit_user_path(@user)
        end
      else
        flash[:notice] = "原密码错误!"
        redirect_to  edit_user_path(@user) 
      end
    else
      flash[:notice] = "输入的两次新密码不一致！"
      redirect_to edit_user_path(@user)
    end
  end       
end

app/views/users/_info.html.erb
<div class="box">
  <div class="userinfo">
    <fieldset>
      <legend>用户基本信息</legend>

      <div class="pull-right avatar_big"><%= getavatar(@user, @user.avatar? ? :big : :normal ) %></div>
      <dl class="dl-horizontal">
        <dt>昵称:</dt>
        <dd><%= @user.netname %> </dd>
        <dt>注册日期:</dt>
        <dd><%= I18n.l(@user.created_at ,:format => :long) %></dd>
        <dt>个性签名</dt><dd>.</dd>
        <dt>腾讯微博</dt><dd>.</dd>
        <dt>手机号码</dt><dd>.</dd>
        <% if ( current_user.admin? or current_user.id == @user.id) %>
        <dt>登录名</dt><dd><%= @user.username %></dd>
        <dt>真实姓名</dt><dd><%= @user.truename %>
        <dt>OACODE</dt><dd><%= @user.oacode %>
        <dt>Telephone</dt><dd><%= @user.telephone %></dd>
        <% end %>
      </dl>
    </fieldset>
  </div>
</div>  

app/views/users/_replies.html.erb
<ul class="recent_replies"
  <% replies.each do |reply| %>
    <% next if reply.topic.blank? %>
    <li>
      <div class= "title">
        <%= link_to(reply.topic.title, topic_path(reply.topic_id)) %>
        <span class="info"> at <%= time_ago_in_words(reply.created_at) %> </span>
      </div>
      <div class="body">
        <%= raw reply.content %>  
      </div>
    </li>
  <% end %>
</ul>

app/views/users/_topics.html.erb
<div class="recent_topics box">
  <h2 class="title">最近发表的帖子</h2>
  <ul>
    <li>
      <span class="node"><%= link_to topic.node.name,topic.node %></span>
      <%= link_to topic.title, topic %>
      <span class="info"> as <%= time_ago_in_words(created_at) %> </span>
    <li>
  </ul>
</div>

app/views/users/edit.html.erb
<% @title = "用户信息修改" %>
<%= render "shared/breadcrumb",links:[["首页",root_path],["用户",""]] %>
<%= notice_message %>
<div id="main" class="container-fluid">
  <div class="content">
    <%= render "shared/error_messages",:target => @user%> 
    <div class="box">
      <%= simple_form_for @user,:html =>{:class =>"form-horizontal",:multipart => true} do |f| %>
        <fieldset> 
        <legend>修改基本资料</legend>
    
        <div class="pull-right avatar_big"><%= getavatar(@user, @user.avatar? ? :big : :normal ) %></div>
        <div class="pull-left">
          <div class="control-group"><%= f.label :netname,"论坛昵称" ,:class => "control-label"%> <%= f.text_field :netname %></div>
          <div class="control-group"><label class ="control-label">选择头像 </label> <%= f.file_field :avatar %></div>
          <div class="control-group"><label class= "control-label"></label><%= f.submit "修改",:class => "btn btn-primary" %></div>
        </div>
        </fieldset>
       <% end %>
    </div>
    <div class = "box">
      <%= form_tag "/changepass", :class => "form-horizontal" do %>
      <fieldset>
        <legend>修改密码</legend>
        <div class="control-group"><label class="control-label">原密码</label><%= password_field_tag :oldpass %></div>
        <div class="control-group"><label class="control-label">新密码</label><%= password_field_tag :newpass %></div>
        <div class="control-group"><label class="control-label">重复新密码</label><%= password_field_tag :newpass_confirm %></div>
        <div class="control-group"><label class="control-label"></label><%= submit_tag "修改密码",:class =>"btn btn-primary" ,:id => "up"%></div>
      </fieldset>
      <% end %>
    </div>
  </div>
  <%= render "shared/sidebar" %>
</div>

app/views/users/index.html.erb
<% @title = "会员列表" %>
<%= render "shared/breadcrumb",links:[["首页",root_path],["用户",""]] %>
<div id="main" class="container-fluid">
    <div class="user_list box clearfix">
    <% if admin?(current_user) and @unusers.count > 0  %>
    <div class="user_list box clearfix">
      <fieldset>
      <legend>需认证会员</legend>
      <% @unusers.each do |user| %> 
        <div class="span1">
          <div><a href=<%= user_path(user)%>><%= getavatar(user,:normal) %></a> </div>
          <div><a href=<%= user_path(user)%>><%= user.netname %></a></div>
        </div>
      <% end %> 
      </fieldset>
    </div>
  <% end %>
      <fieldset>
      <legend>已认证会员</legend>
      <% @newusers.each do |user| %> 
        <div class="span1">
          <div><a href=<%= user_path(user)%>><%= getavatar(user,:normal) %></a> </div>
          <div><a href=<%= user_path(user)%>><%= user.netname %></a></div>
        </div>
      <% end %> 
      </fieldset>
      <div class="row-fuild"><%= will_paginate @newusers %></div>
    </div>
</div>

app/views/users/index.html.haml
%section#users_list
  %strong 会员列表
  %table
    - User.all.each do |user|
      %tr
        %td 
          %img(src="/assets/normal.png")
        %td= link_to user.netname , user
        %td= user.last_sign_in_at

app/views/users/new.html.erb
<% @title = "用户注册" %>
<%= render "shared/breadcrumb" ,links: [["首页",root_path],["用户",""]] %>
<%= notice_message %>
<div id="main" class="container-fluid">
  <div class="content">
    <div class="box">
     <%= form_for @user ,:html=>{ :class => "form-horizontal"} do |f| %>
      <fieldset>
        <legend>用户注册</legend>
          <%= render "shared/error_messages",:target => @user%> 

          <div class="control-group">
            <%= f.label :oacode,:class =>"control-label" %>
            <%= f.text_field :oacode %><span class="help-inline">* 注册成功后，用OA号登录论坛。</span>
          </div>

          <div class="control-group">
            <%= f.label :oapass,:class =>"control-label" %>
            <%= f.password_field :oapass %><span class="help-inline">* 使用OA用户名密码注册，注册成功后，可以修改论坛密码。</span>
          </div>
          <div class="control-group">
            <%= f.label :netname ,:class => "control-label" %>
            <%= f.text_field :netname %><span class="help-inline">* 在论坛中公开显示的名称，注册后可以修改。</span>
          </div>
          
          <div class="control-group"> 
            <label class="control-label"></label>
            <%= f.submit "注册", :class => "btn btn-primary" %>
          </div>
      </fieldset>
    <% end %>
    

  </div>
 </div>
  <%= render "shared/userreg_sidebar" %>
</div>

app/views/users/show.html.erb
<% @title = @user.netname %>
<%= render "shared/breadcrumb",links:[["首页",root_path],["用户",users_path],[@user.netname,""]] %>
<div id="main" class="container-fluid">
<div class="content">
  <%= render "info" %>
  <div class ="recent_topics box">
    <h2 class="title">最近发表的帖子列表</h2>
    <ul>
      <% @topics.each do |item| %>
        <li>
          <span class="node"><%= link_to item.node.name,item.node,:class=>"node" %> </span>
          <%= link_to  item.title,item %>
          <span class="info"> at <%= time_ago_in_words(item.created_at) %> </span>
        </li>
      <% end %>
    </ul>
  </div>

  <div class = "box">
    <h2 class="title"> 最近回复</h2>
    <%= render "replies",:replies => @replies %>
  </div>

</div>

<%= render "shared/sidebar" %>
</div>

app/views/users/show.html.haml
= render 'shared/breadcrumb' ,links:[["首页",root_path]]
%section#user.box
  %h1 个人信息
  %img(src="/assets/normal.png")
  %dl
    %dt.span1 ID:
    %dd
      %strong= @user.netname
    %dt.span1 姓名：
    %dd= @user.username
    %dt.span1 创建于:
    %dd= @user.created_at
  =link_to "修改",edit_user_path(@user)
%section#user_recent_topics.box
  %section#user_recent_topics_banner.box.info-box
    %span 最近发布的帖子
  %section#user_recent_topics_content.box
    %ul
      - @topics.each do |topic|
        %li
          =link_to topic.node.name,topic.node,class:"node"
          =link_to topic.title,topic
          %span="创建于#{ time_ago_in_words(topic.created_at)}之前"
          
%section#user_recent_replies.box
  %section#user_recent_replies_banner.box.info-box
    %span 最近回复的帖子
  %section#user-rencent_replies_content.box
    %ul
      - @replies.each do |reply|
        %li
          = link_to  reply.topic.title,reply.topic
          %span= "回复于 #{ time_ago_in_words(reply.created_at)} 之前"
          %p=simple_format( reply.content)