config/routes.rb
Second::Application.routes.draw do

  

  resources :nodes
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  
  resources :topics  do
    resources :replies
  end
  
  match "/logout" =>'sessions#logout',:as => "logout"
 
  resources :sessions
  resources :users 
  
  match "/changepass" => "users#changepass",:as => "changepass"  

  root :to =>  'topics#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head> 
  <title><%= @title %></title>
    	<link href="/assets/front.css" rel="stylesheet">
    	<!--[if IE 6]>    
    		<link href="/assets/ie6.min.css" rel="stylesheet">
    	<![endif]-->
  
  <%= javascript_include_tag "application" %>
</head>
<body>
  <div class="navbar  navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand"><strong>南翔人论坛</strong></a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><%= link_to "论坛",topics_path %></li>
            <li><%= link_to "会员",users_path %></li>
          </ul>
          <form class="navbar-search pull-left form-search">
            <input type="text" class="search-query" placeholder="Search">
          </form>
         <ul class="nav pull-right">
            <% if current_user.blank? %>
              <li><%= link_to "登录",new_session_path %></li>
              <li><%= link_to "注册",new_user_path %></li>
            <% else %>
              <li><%= link_to current_user.netname,user_path(current_user) %></li>
              <li><%= link_to "修改资料",edit_user_path(current_user) %></li>
              <li><%= link_to "注销", '/logout' %></li>
          
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container"> 
    <%= yield %> 
    <hr>
  </div>
  <footer class="footer">
    <div class="container">
     <p> <center>&copy; 南翔集团2012 <a href ="#"> 皖ICP备05002863号</a><center> </p>
    </div>
  </footer>
  

</body>

app/views/layouts/application.html.haml
<!DOCTYPE html>
<html>
<head>
  <title>Second</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">南翔人论坛</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">首页</a></li>
              <li><a href="#about">论坛</a></li>
              <li><a href="#contact">会员</a></li>
            </ul>
            <ul class="nav pull-right">
              <li><a href="#">登录</a></li>
              <li><a href="#">注册</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        = yield
    <hr>
    <footer class="footer">
      %p &copy; 南翔集团信息中心 2012
    </footer>